server:
  port: 8099
  servlet:
    context-path: /api

# Spring
spring:
  application:
    name: backend
  profiles:
    active: dev
  jpa:
    defer-datasource-initialization: false
  flyway:
    enabled: false
  config:
    import: classpath:application-security.yaml


# JWT Configuration
jwt:
  secret: aflakjdfalafhalkdfhasdflkjahsdfljkahsdfalkjdfhalsdfhalskdfhasldfjahsdfljashdflajshdflasjdfhalskjdfhasljdfhaslkdfhasldfhasldfkjhasldfjashldfjkhasldfjhasdfl
  expiration-ms: 86400000